---
info:
  title: Myallocator Build-To-US API
  version: "5.0"
  contact:
    url: https://www.cloudbeds.com/partner-with-cloudbeds/
  description: |
    # Introduction

    This API allows an OTA ("Online Travel Agency", also called "channel",
    or "travel booking website") to integrate with the myallocator channel
    manager by implementing an API receiver in their environment.

    If you are a property management system (PMS), this is not the API you are
    looking for. Instead please review our
    [PMS API documentation](http://apidocs.myallocator.com/) instead.

    # Getting Started

    ## Becoming A Partner

    To be considered as a partner, please complete our
    [partnership form](https://www.cloudbeds.com/partner-with-cloudbeds/).
    Your application will be placed in a queue to be reviewed for fit and
    compatibility. We will reach out if the partnership is approved.

    If approved, you will be provided with a 72-hour link to our API Credential
    Request form, which will help you create a test account and define your
    channel on myallocator.

    Upon completion of the API Credentialing, you will then have access to your
    Test Account login information, channel ID (`cid`), and the `shared_secret`
    that is required for the API calls.

    At this point, the channel will be hidden from our user base while in
    development and only viewable by your designated test account. You will be
    able to use your trial account as a test harness for sending updates to
    your channel. We request that you update our team at least once every two
    weeks while in development with your estimated completion date.

    Partners that fail to provide an estimated completion date may have their
    participation eligibility rescinded.

    We have a self-certification tool. Once you have finished your development
    process, you will be guided on how to use this tool in order to test and
    get your integration certified.

    Once you get certified, our team will inform you of the next steps,
    including providing us with:

    * Logos
    * Information about your service
    * Property setup information (obtaining setup credentials, activating the channel manager, etc.)
    * Contact Information to various departments of your business (support, marketing, etc.)

    When everything is tested and all documentation is received your application
    will be released in a beta stage for 2-3 weeks before going live.

    ## Flow

    For a new property to connect to the OTA they will go to the channel setup
    on myallocator, and either enter their OTA credentials, or go through some
    activation process, where the OTA is automatically emailed to enable the
    property and a support team member of myallocator sets the credentials.

    The property owner then maps the rooms and rate plans to complete the
    connection.

    After a property has been setup, myallocator will push a full refresh to the
    OTA. This means myallocator sends all availability, rates and restrictions
    for the next 2+ years (depending on how many years of ARI data the OTA
    supports) for all rooms and rate plans. After this initial sync has been
    completed myallocator will update the OTA whenever there is a change to
    ARI, eg. because a booking has been imported or pricing has been altered.

    Myallocator will poll for bookings in regular configurable intervals.
    Bookings can and should be sent via a callback to myallocator to speed up
    the import.

    # Booking Format

    The full booking format is
    [documented here](https://github.com/MyAllocator/build2us-apidocs/blob/gh-pages/booking_format_b2u.md).
    Please take note of which fields are required and which fields are optional.

    # Error Codes

    You can respond with error IDs listed in our
    [error code](https://apidocs.myallocator.com/ota-errors.html) list. Please
    use the numeric codes in the `ID` column. Only errors whose code starts with
    `FAULT.OTA.` are supported.

    # Rate Plans

    On myallocator rooms and rate plans have a one-to-many relationship. This
    means that a room has one or more rate plans, and each rate plan has
    exactly one room. For the `ARIUpdate` calls we can send different
    `ota_rate_id` values for the same `ota_room_id`. Rates and restrictions are
    tied to rate plans, while availability is tied to rooms, so the `units`
    will be constant across different rate plans for the same dates and for the
    same room, but rates and restrictions can vary. To close off a rate plan we
    are using the `close` flag.

    # FAQ

    ## Terminology

    * OTA: Online travel agency (ex: booking.com, or competitor)
    * cid: Channel ID - a two to four character code used by myallocator uniquely identify a OTA.
    * guid: Globally unique identifier, a unique 36 character code which identifies a request. Useful for seeing if a request is a retry and for debugging.f

    ## Requests

    Myallocator will send requests to the OTA with content-type
    `application/json`, with the payload being in the body of the request. Gzip
    compression and keep-alives will be used if supported. HTTPS
    (SSL encryption) is required for the OTA's endpoint.

    HTTP response codes from myallocator should always be 200. They have the
    content-type `application/json`.

    ## Required API calls

    As a minimum these API calls need to be implemented on the OTA side:

    * HealthCheck
    * SetupProperty
    * GetRoomTypes
    * GetRatePlans
    * ARIUpdate
    * GetBookingList
    * GetBookingId
    * CreateProperty

    If the OTA has multiple properties under one user account these API calls
    are required in addition:

    * GetSubProperties

openapi: 3.0.0
servers:
  - url: https://api.your-ota.com/myallocator
    description: OTA endpoint

paths:
  /HealthCheck:
    $ref: methods/HealthCheck.yaml
  /SetupProperty:
    $ref: methods/SetupProperty.yaml
  /GetRoomTypes:
    $ref: methods/GetRoomTypes.yaml
  /GetRatePlans:
    $ref: methods/GetRatePlans.yaml
  /ARIUpdate:
    $ref: ./methods/ARIUpdate.yaml
  /GetBookingList:
    $ref: methods/GetBookingList.yaml
  /GetBookingId:
    $ref: methods/GetBookingId.yaml
  /CancelBooking:
    $ref: ./methods/CancelBooking.yaml
  /CreateProperty:
    $ref: methods/CreateProperty.yaml
  /GetSubProperties:
    $ref: methods/GetSubProperties.yaml

  /ARIFullRefresh:
    $ref: methods/ARIFullRefresh.yaml
  /BookingCreate:
    $ref: methods/BookingCreate.yaml
  /NotifyBooking:
    $ref: methods/NotifyBooking.yaml
  /RoomInfo:
    $ref: methods/RoomInfo.yaml
